# docker build -f Dockerfile.ubuntu -t dev/hello-there:ubuntu .

ARG BASEIMAGE=ubuntu
ARG BASETAG=20.04

FROM ${BASEIMAGE}:${BASETAG} as stage_builder

WORKDIR /usr/src/hello
    
COPY ./ubuntu/src .

RUN \
    apt-get update \
    && apt-get install -y --no-install-recommends \
        gcc \
        libc6-dev \
    && gcc hello.c -o hello

FROM ${BASEIMAGE}:${BASETAG} as stage_final

WORKDIR /usr/src/hello

COPY --from=stage_builder /usr/src/hello .
    
CMD ["./hello"]
