#!/bin/bash -xe

declare platform

case "${DOCKER_TAG}" in

    *-amd64 )
        platform="linux/amd64" ;;
    *-386 )
        platform="linux/386" ;;
    *-arm64 )
        platform="linux/arm64" ;;
    *-arm64v8 )
        platform="linux/arm64/v8" ;;
    *-armv7 )
        platform="linux/arm/v7" ;;
    *-armv6 )
        platform="linux/arm/v6" ;;

    *alpine )
        platform="linux/amd64,linux/386,linux/arm64,linux/arm/v7,linux/arm/v6" ;;

    *debian )
        platform="linux/amd64,linux/386" ;;

    *ubuntu-18.04 )
        platform="linux/amd64,linux/386" ;;
    *ubuntu-20.04 )
        platform="linux/amd64" ;;
    *ubuntu-20.10 )
        platform="linux/amd64" ;;
    *ubuntu-21.04 )
        platform="linux/amd64" ;;

    * )
        echo "Will not build unknown tag '${DOCKER_TAG}'."
        ;;
esac

case "${DOCKER_TAG}" in
    *ubuntu-18.04* ) BASETAG="18.04" ;;
    *ubuntu-20.04* ) BASETAG="20.04" ;;
    *ubuntu-20.10* ) BASETAG="20.10" ;;
    *ubuntu-21.04* ) BASETAG="21.04" ;;
esac

docker buildx build \
    -f "${DOCKERFILE_PATH}" \
        ${BASETAG:+--build-arg BASETAG=${BASETAG}} \
        --platform "${platform}" \
        --push \
    -t "${DOCKER_REPO}":"${DOCKER_TAG}" .
