#!/bin/bash -xe

case ${DOCKER_TAG} in

    *alpine* )

        docker buildx build \
            -f ${DOCKERFILE_PATH} \
                --platform linux/amd64,linux/arm64,linux/arm/v7,linux/arm/v6,linux/386 \
                --push \
            -t ${DOCKER_REPO}:${DOCKER_TAG} .
        ;;

    *debian* )

        docker buildx build \
            -f ${DOCKERFILE_PATH} \
                --platform linux/amd64,linux/386 \
                --push \
            -t ${DOCKER_REPO}:${DOCKER_TAG} .
        ;;

    * )
        echo "Will not build unknown tag '${DOCKER_TAG}'."
        ;;
esac
